<a href="https://colab.research.google.com/github/America1096/AnalisisDeTextos/blob/master/Proyecto2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [14]:
data = pd.read_csv('master.csv', encoding='latin-1')
data.shape

(27820, 12)

In [15]:
data.columns

Index(['country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation'],
      dtype='object')

In [0]:
data = data[["country", "year", "sex", "age", "suicides_no", "generation"]] #Se dejan unicamente las columnas necesarias

In [17]:
print(data)

          country  year     sex          age  suicides_no       generation
0         Albania  1987    male  15-24 years           21     Generation X
1         Albania  1987    male  35-54 years           16           Silent
2         Albania  1987  female  15-24 years           14     Generation X
3         Albania  1987    male    75+ years            1  G.I. Generation
4         Albania  1987    male  25-34 years            9          Boomers
5         Albania  1987  female    75+ years            1  G.I. Generation
6         Albania  1987  female  35-54 years            6           Silent
7         Albania  1987  female  25-34 years            4          Boomers
8         Albania  1987    male  55-74 years            1  G.I. Generation
9         Albania  1987  female   5-14 years            0     Generation X
10        Albania  1987  female  55-74 years            0  G.I. Generation
11        Albania  1987    male   5-14 years            0     Generation X
12        Albania  1988  female    75+ years            2  G.I. Generation
13        Albania  1988    male  15-24 years           17     Generation X
14        Albania  1988    male    75+ years            1  G.I. Generation
15        Albania  1988    male  35-54 years           14           Silent
16        Albania  1988    male  55-74 years            4  G.I. Generation
17        Albania  1988  female  15-24 years            8     Generation X
18        Albania  1988  female  55-74 years            3  G.I. Generation
19        Albania  1988  female  25-34 years            5          Boomers
20        Albania  1988    male  25-34 years            5          Boomers
21        Albania  1988  female  35-54 years            4           Silent
22        Albania  1988  female   5-14 years            0     Generation X
23        Albania  1988    male   5-14 years            0     Generation X
24        Albania  1989    male    75+ years            2  G.I. Generation
25        Albania  1989    male  25-34 years           18          Boomers
26        Albania  1989    male  35-54 years           15           Silent
27        Albania  1989    male  55-74 years            6  G.I. Generation
28        Albania  1989    male  15-24 years           12     Generation X
29        Albania  1989  female  35-54 years            7           Silent
...           ...   ...     ...          ...          ...              ...
27790  Uzbekistan  2012  female  25-34 years          148       Millenials
27791  Uzbekistan  2012  female  35-54 years           89     Generation X
27792  Uzbekistan  2012    male   5-14 years           67     Generation Z
27793  Uzbekistan  2012  female  55-74 years           25          Boomers
27794  Uzbekistan  2012  female    75+ years            4           Silent
27795  Uzbekistan  2012  female   5-14 years           16     Generation Z
27796  Uzbekistan  2013    male  35-54 years          481     Generation X
27797  Uzbekistan  2013    male  25-34 years          328       Millenials
27798  Uzbekistan  2013  female  15-24 years          323       Millenials
27799  Uzbekistan  2013    male  15-24 years          320       Millenials
27800  Uzbekistan  2013    male  55-74 years          119          Boomers
27801  Uzbekistan  2013    male    75+ years           13           Silent
27802  Uzbekistan  2013  female  25-34 years          146       Millenials
27803  Uzbekistan  2013  female  35-54 years           99     Generation X
27804  Uzbekistan  2013  female    75+ years            8           Silent
27805  Uzbekistan  2013    male   5-14 years           61     Generation Z
27806  Uzbekistan  2013  female  55-74 years           21          Boomers
27807  Uzbekistan  2013  female   5-14 years           31     Generation Z
27808  Uzbekistan  2014    male  35-54 years          519     Generation X
27809  Uzbekistan  2014    male  25-34 years          318       Millenials
27810  Uzbekistan  2014  female  15-24 years          347       Millenials
27811  Uzbekistan  2014    male  55-74 years          144          Boomers
27812  Uzbekistan  2014    male  15-24 years          347       Millenials
27813  Uzbekistan  2014    male    75+ years           17           Silent
27814  Uzbekistan  2014  female  25-34 years          162       Millenials
27815  Uzbekistan  2014  female  35-54 years          107     Generation X
27816  Uzbekistan  2014  female    75+ years            9           Silent
27817  Uzbekistan  2014    male   5-14 years           60     Generation Z
27818  Uzbekistan  2014  female   5-14 years           44     Generation Z
27819  Uzbekistan  2014  female  55-74 years           21          Boomers

[27820 rows x 6 columns]

In [18]:
data[data.suicides_no <= 10][data.suicides_no > 0] #Se consideran los suicidios de 1 a 10

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

          country  year     sex          age  suicides_no       generation
3         Albania  1987    male    75+ years            1  G.I. Generation
4         Albania  1987    male  25-34 years            9          Boomers
5         Albania  1987  female    75+ years            1  G.I. Generation
6         Albania  1987  female  35-54 years            6           Silent
7         Albania  1987  female  25-34 years            4          Boomers
8         Albania  1987    male  55-74 years            1  G.I. Generation
12        Albania  1988  female    75+ years            2  G.I. Generation
14        Albania  1988    male    75+ years            1  G.I. Generation
16        Albania  1988    male  55-74 years            4  G.I. Generation
17        Albania  1988  female  15-24 years            8     Generation X
18        Albania  1988  female  55-74 years            3  G.I. Generation
19        Albania  1988  female  25-34 years            5          Boomers
20        Albania  1988    male  25-34 years            5          Boomers
21        Albania  1988  female  35-54 years            4           Silent
24        Albania  1989    male    75+ years            2  G.I. Generation
27        Albania  1989    male  55-74 years            6  G.I. Generation
29        Albania  1989  female  35-54 years            7           Silent
30        Albania  1989  female  15-24 years            5     Generation X
31        Albania  1989  female  25-34 years            2          Boomers
32        Albania  1989  female  55-74 years            1  G.I. Generation
37        Albania  1992    male  15-24 years            9     Generation X
38        Albania  1992    male  55-74 years            5           Silent
39        Albania  1992    male  25-34 years            7          Boomers
40        Albania  1992  female  15-24 years            7     Generation X
41        Albania  1992  female  25-34 years            4          Boomers
42        Albania  1992  female  35-54 years            2          Boomers
43        Albania  1992  female  55-74 years            1           Silent
49        Albania  1993    male  55-74 years            7           Silent
50        Albania  1993    male    75+ years            1  G.I. Generation
51        Albania  1993    male  25-34 years            9          Boomers
...           ...   ...     ...          ...          ...              ...
27519     Uruguay  2012  female   5-14 years            1     Generation Z
27530     Uruguay  2013  female   5-14 years            5     Generation Z
27531     Uruguay  2013    male   5-14 years            3     Generation Z
27542     Uruguay  2014    male   5-14 years            1     Generation Z
27554     Uruguay  2015    male   5-14 years            3     Generation Z
27555     Uruguay  2015  female   5-14 years            2     Generation Z
27579  Uzbekistan  1991  female   5-14 years            7       Millenials
27591  Uzbekistan  1992  female   5-14 years            8       Millenials
27603  Uzbekistan  1993  female   5-14 years            7       Millenials
27609  Uzbekistan  1994    male    75+ years           10  G.I. Generation
27615  Uzbekistan  1994  female   5-14 years            3       Millenials
27627  Uzbekistan  1995  female   5-14 years            7       Millenials
27639  Uzbekistan  1996  female   5-14 years           10       Millenials
27651  Uzbekistan  1997  female   5-14 years            9       Millenials
27663  Uzbekistan  1998  female   5-14 years            7       Millenials
27719  Uzbekistan  2003  female    75+ years           10           Silent
27728  Uzbekistan  2004    male    75+ years            9           Silent
27730  Uzbekistan  2004  female    75+ years           10           Silent
27735  Uzbekistan  2004  female   5-14 years            4       Millenials
27744  Uzbekistan  2005  female    75+ years            7           Silent
27747  Uzbekistan  2005  female   5-14 years           10       Millenials
27754  Uzbekistan  2009    male    75+ years            7           Silent
27755  Uzbekistan  2009  female    75+ years            7           Silent
27765  Uzbekistan  2010    male    75+ years            9           Silent
27769  Uzbekistan  2010  female    75+ years            5           Silent
27778  Uzbekistan  2011    male    75+ years           10           Silent
27782  Uzbekistan  2011  female    75+ years            5           Silent
27794  Uzbekistan  2012  female    75+ years            4           Silent
27804  Uzbekistan  2013  female    75+ years            8           Silent
27816  Uzbekistan  2014  female    75+ years            9           Silent

[6642 rows x 6 columns]

In [0]:
maxSuc = int(data[["suicides_no"]].max())
minSuc = int(data[["suicides_no"]].min())

In [20]:
data[data.suicides_no == maxSuc]

                  country  year   sex          age  suicides_no generation
20996  Russian Federation  1994  male  35-54 years        22338    Boomers

In [21]:
data[data.suicides_no == minSuc]

                    country  year  ... suicides_no       generation
9                   Albania  1987  ...           0     Generation X
10                  Albania  1987  ...           0  G.I. Generation
11                  Albania  1987  ...           0     Generation X
22                  Albania  1988  ...           0     Generation X
23                  Albania  1988  ...           0     Generation X
33                  Albania  1989  ...           0     Generation X
34                  Albania  1989  ...           0  G.I. Generation
35                  Albania  1989  ...           0     Generation X
44                  Albania  1992  ...           0       Millenials
45                  Albania  1992  ...           0  G.I. Generation
46                  Albania  1992  ...           0       Millenials
47                  Albania  1992  ...           0  G.I. Generation
59                  Albania  1993  ...           0  G.I. Generation
71                  Albania  1994  ...           0       Millenials
107                 Albania  1997  ...           0           Silent
119                 Albania  1998  ...           0  G.I. Generation
131                 Albania  1999  ...           0       Millenials
142                 Albania  2000  ...           0       Millenials
143                 Albania  2000  ...           0           Silent
179                 Albania  2003  ...           0       Millenials
192                 Albania  2005  ...           0       Millenials
193                 Albania  2005  ...           0     Generation X
194                 Albania  2005  ...           0          Boomers
195                 Albania  2005  ...           0       Millenials
196                 Albania  2005  ...           0           Silent
197                 Albania  2005  ...           0           Silent
198                 Albania  2005  ...           0       Millenials
199                 Albania  2005  ...           0     Generation X
200                 Albania  2005  ...           0          Boomers
201                 Albania  2005  ...           0       Millenials
...                     ...   ...  ...         ...              ...
26427  United Arab Emirates  2006  ...           0           Silent
26436  United Arab Emirates  2007  ...           0     Generation Z
26437  United Arab Emirates  2007  ...           0           Silent
26438  United Arab Emirates  2007  ...           0     Generation Z
26439  United Arab Emirates  2007  ...           0           Silent
26447  United Arab Emirates  2008  ...           0     Generation Z
26448  United Arab Emirates  2008  ...           0           Silent
26449  United Arab Emirates  2008  ...           0           Silent
26450  United Arab Emirates  2008  ...           0     Generation Z
26451  United Arab Emirates  2008  ...           0           Silent
26460  United Arab Emirates  2009  ...           0           Silent
26461  United Arab Emirates  2009  ...           0           Silent
26462  United Arab Emirates  2009  ...           0     Generation Z
26463  United Arab Emirates  2009  ...           0           Silent
26473  United Arab Emirates  2010  ...           0     Generation Z
26474  United Arab Emirates  2010  ...           0           Silent
26475  United Arab Emirates  2010  ...           0     Generation Z
26547        United Kingdom  1990  ...           0     Generation X
26571        United Kingdom  1992  ...           0       Millenials
26619        United Kingdom  1996  ...           0       Millenials
27243               Uruguay  1986  ...           0     Generation X
27267               Uruguay  1988  ...           0     Generation X
27279               Uruguay  1989  ...           0     Generation X
27315               Uruguay  1994  ...           0       Millenials
27327               Uruguay  1995  ...           0       Millenials
27363               Uruguay  1998  ...           0       Millenials
27459               Uruguay  2006  ...           0       Millenials
27471               Uruguay  2007  ...           0     Generation Z
27495               Uruguay  2009  ...           0     Generation Z
27543               Uruguay  2014  ...           0     Generation Z

[4281 rows x 6 columns]

In [22]:
gen = set(data["generation"])
mayor = 0
for g in gen:
  total = data[data.generation == g].sum()
  if mayor < total["suicides_no"]:
    mayor = total["suicides_no"]
    generacion = g
  print("Generacion =", g, ", Total de suicidios =",total["suicides_no"])

print("\nGeneracion con mas suicidios =", generacion, ", con =", mayor, "suicidios")

Generacion = Generation Z , Total de suicidios = 15906
Generacion = Generation X , Total de suicidios = 1532804
Generacion = Silent , Total de suicidios = 1781744
Generacion = Millenials , Total de suicidios = 623459
Generacion = G.I. Generation , Total de suicidios = 510009
Generacion = Boomers , Total de suicidios = 2284498

Generacion con mas suicidios = Boomers , con = 2284498 suicidios

In [23]:
sexo = set(data["sex"])
mayor = 0
totalSuicidios = data[["suicides_no"]].sum() #Total de suicidios
for s in sexo:
  total = data[data.sex == s].sum()
  porc = float((total["suicides_no"]*100)/totalSuicidios)
  if mayor < total["suicides_no"]:
    mayor = total["suicides_no"]
    sexom = s
  print("Sexo =", s, ", total de suicidios =",total["suicides_no"], ", Porcentaje = %", porc)

print("\nSexo con mas suicidios =", sexom, ", con =", mayor, "suicidios")

Sexo = male , total de suicidios = 5188910 , Porcentaje = % 76.89073886924643
Sexo = female , total de suicidios = 1559510 , Porcentaje = % 23.10926113075357

Sexo con mas suicidios = male , con = 5188910 suicidios

In [25]:
age = set(data["age"])
mayor = 0
totalSuicidios = data[["suicides_no"]].sum() #Total de suicidios
for s in age:
  total = data[data.age == s].sum()
  porc = float((total["suicides_no"]*100)/totalSuicidios)
  if mayor < total["suicides_no"]:
    mayor = total["suicides_no"]
    agem = s
  print("Rango de edad =", s, ", total de suicidios =",total["suicides_no"], ", Porcentaje = %", porc)

print("\nRango de edad con mas suicidios =", agem, ", con =", mayor, "suicidios")

Rango de edad = 25-34 years , total de suicidios = 1123912 , Porcentaje = % 16.65444652229707
Rango de edad = 5-14 years , total de suicidios = 52264 , Porcentaje = % 0.7744627631356673
Rango de edad = 15-24 years , total de suicidios = 808542 , Porcentaje = % 11.981204489347135
Rango de edad = 55-74 years , total de suicidios = 1658443 , Porcentaje = % 24.575278361453496
Rango de edad = 35-54 years , total de suicidios = 2452141 , Porcentaje = % 36.33652025214791
Rango de edad = 75+ years , total de suicidios = 653118 , Porcentaje = % 9.67808761161872

Sexo con mas suicidios = 35-54 years , con = 2452141 suicidios

In [42]:
mayor = 0
totalSuicidios = data[["suicides_no"]].sum() #Total de suicidios

for i in range(1981, 2021, 10):
  print(f"Década de {i - 1}s")
  total = data[data.year.between(i , i+9)].sum()
  porc = float((total["suicides_no"]*100)/totalSuicidios)
  if mayor < total["suicides_no"]:
    mayor = total["suicides_no"]
    yearm = i
  print("total de suicidios =",total["suicides_no"], ", Porcentaje = %", porc)

print("\nDécada con mas suicidios =", yearm-1, "'s, con =", mayor, "suicidios")

Década de 1980s
total de suicidios = 838206 , Porcentaje = % 12.4207740478512
Década de 1990s
total de suicidios = 2355677 , Porcentaje = % 34.90708936313982
Década de 2000s
total de suicidios = 2422467 , Porcentaje = % 35.89680251080994
Década de 2010s
total de suicidios = 1132070 , Porcentaje = % 16.775334078199045

Década con mas suicidios = 2000 's, con = 2422467 suicidios

In [67]:
country = set(data["country"])
mayor = 0
totalSuicidios = data[["suicides_no"]].sum() #Total de suicidios
auxl = []
for c in country:
  total = data[data.country == c].sum()
  porc = float((total["suicides_no"]*100)/totalSuicidios)
  auxl.append([total["suicides_no"], c, porc])

auxl.sort()
tam = len(auxl)

print("Los diez países con mayor número de suicidios")
print("No. Suicidios\t\tPaís\t\tPorcentaje")
for x in range(10):
  for y in range(3):
    print(auxl[tam-(x+1)][y], end="\t\t")
    
  print()

Los diez países con mayor número de suicidios
No. Suicidios		País		Porcentaje
1209742		Russian Federation		17.926299785727622
1034013		United States		15.32229766374944
806902		Japan		11.956902504586258
329127		France		4.87709715755688
319950		Ukraine		4.741109770879702
291262		Germany		4.316002856965038
261730		Republic of Korea		3.8783893118685557
226613		Brazil		3.358015654034574
139098		Poland		2.0611935830905606
136805		United Kingdom		2.0272152592755046

Se obtiene un vocabulario en base a las generaciones

In [124]:
genVoc = set() #Tipos de generaciones
for generaciones in data.generation:
  if generaciones.strip().split():
    genVoc = genVoc.union(generaciones.split())
    
V = {}
gener = set(data["generation"]) #Se obtiene de la base de datos un conjunto en base a la generacion

[V.setdefault(key,0) for key in genVoc] #Se crea diccionario para los tipos de generaciones

[0, 0, 0, 0, 0, 0, 0]